name: CD (Snapshot deployment)


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      id: build_code
      with:
        distribution: temurin
        java-version: 17
        cache: maven
        server-id: sonatype-nexus-snapshots
        server-username: NEXUS_REPO_USER
        server-password: NEXUS_REPO_PASSWORD
    - name: deploy code
      env:
        NEXUS_REPO_USER:     ${{ secrets.NEXUS_REPO_USER }}
        NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
      run: |
        make deploy
    - uses: actions/setup-java@v3
      id: build_docs
      with:
        distribution: temurin
        java-version: 17
        cache: maven
        server-id: github
        server-username: github
        server-password: SITE_DEPLOY
    - name: deploy documentation
      env:
        SITE_DEPLOY: ${{ secrets.SITE_DEPLOY }}
      run: |
        make deploy-docs
